version: '3.7'
services:
  jenkins:
    image: jane97/jenkins_lts:1.0
    restart: always
    container_name: 'jenkins'
    hostname: 'jenkins'
    privileged: true
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - 'jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/bin/docker:/usr/bin/docker'
      - '/app:/app'
      - '/root/.bash_profile:/root/.bash_profile'
volumes:
  jenkins_home:

