spring:
  profiles:
    active: local
  application:
    name: jti
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    check-template-location: true
    mode: LEGACYHTML5
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#  jmx:
#    enabled: false
server:
  port: 6060

  
  
#spring.application.name= jti
#server.port= 6060
#spring.mysql.datasource.jndi-name= true
#spring.datasource.initialize= false
#ttaeinee.datasource.jndi.config-location: classpath:mybatis/mybatis-config-mysql.xml
#ttaeinee.datasource.jndi.mapper-locations: classpath:mybatis/**/mapper/jndi1/*mapper.sqlx
#spring.jmx.enabled= false
#spring.datasource.jndi-name= java:comp/env/jdbc/TAEIN_DB
#mybatis.mapper-locations= classpath:mybatis-config.xml
#mybatis.config-location= classpath:mapper/jndi1/mysqlJndiMapper.sqlx

#java:/comp/env/


db:
  cache:
    default-expire-time: 30
    expires:
      oList: 60
      mList: 60